"""Add new tables and columns

Revision ID: 492ff06e3215
Revises: 1a31ce608336
Create Date: 2025-11-19 13:27:54.942633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492ff06e3215'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'booth_states',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'clients',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'org_unit_types',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'roles',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'org_units',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('type_id', sa.Integer(), nullable=True, server_default=sa.text("0")),
        sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('client_id', sa.Uuid(), nullable=False),
        sa.Column('parent_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id']),
        sa.ForeignKeyConstraint(['parent_id'], ['org_units.id']),
        sa.ForeignKeyConstraint(['type_id'], ['org_unit_types.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'phone_booths',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('state_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('client_id', sa.Uuid(), nullable=True),
        sa.Column('org_unit_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('working_hours', sa.Integer(), nullable=False, server_default=sa.text("8")),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id']),
        sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id']),
        sa.ForeignKeyConstraint(['state_id'], ['booth_states.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'sensors',
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('mqtt_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=sa.text("'active'")),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('phone_booth_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.ForeignKeyConstraint(['phone_booth_id'], ['phone_booths.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial_number')
    )

    op.create_table(
        'sensor_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('sensor_id', sa.Uuid(), nullable=False),
        sa.Column('phone_booth_id', sa.Uuid(), nullable=False),
        sa.Column('client_id', sa.Uuid(), nullable=False),
        sa.Column('org_unit_id', sa.Uuid(), nullable=False),
        sa.Column('state_id', sa.Integer(), nullable=False),
        sa.Column('event_time_utc', sa.DateTime(), nullable=False),
        sa.Column('received_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id']),
        sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id']),
        sa.ForeignKeyConstraint(['phone_booth_id'], ['phone_booths.id']),
        sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'usage_sessions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('phone_booth_id', sa.Uuid(), nullable=False),
        sa.Column('client_id', sa.Uuid(), nullable=False),
        sa.Column('org_unit_id', sa.Uuid(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id']),
        sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id']),
        sa.ForeignKeyConstraint(['phone_booth_id'], ['phone_booths.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('client_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('org_unit_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'org_units', ['org_unit_id'], ['id'])
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'org_unit_id')
    op.drop_column('user', 'client_id')
    op.drop_table('usage_sessions')
    op.drop_table('phone_booths')
    op.drop_table('org_units')
    op.drop_table('sensors')
    op.drop_table('sensor_events')
    op.drop_table('roles')
    op.drop_table('org_unit_types')
    op.drop_table('clients')
    op.drop_table('booth_states')
    # ### end Alembic commands ###
