"""Add phone booths working hours related columns

Revision ID: 89504fe18b2f
Revises: 492ff06e3215
Create Date: 2025-11-28 10:55:32.284117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from datetime import time


# revision identifiers, used by Alembic.
revision = '89504fe18b2f'
down_revision = '492ff06e3215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_booths', sa.Column('workday_start', sa.Time(), nullable=False, server_default=str(time(9, 0))))
    op.add_column('phone_booths', sa.Column('workday_end', sa.Time(), nullable=False, server_default=str(time(17, 0))))
    op.add_column('phone_booths', sa.Column('working_days_mask', sa.Integer(), nullable=False, server_default=str(31)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_booths', 'working_days_mask')
    op.drop_column('phone_booths', 'workday_end')
    op.drop_column('phone_booths', 'workday_start')
    # ### end Alembic commands ###
