/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPhoneBoothsRouteImport } from './routes/_layout/phone-booths'
import { Route as LayoutMqttItemsRouteImport } from './routes/_layout/mqtt-items'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutBoothCalendarRouteImport } from './routes/_layout/booth-calendar'
import { Route as LayoutUsageReportsTableRouteImport } from './routes/_layout/usage-reports/table'
import { Route as LayoutUsageReportsChartsRouteImport } from './routes/_layout/usage-reports/charts'
import { Route as LayoutAdminClientsRouteImport } from './routes/_layout/admin/clients'
import { Route as LayoutAdminAdminRouteImport } from './routes/_layout/admin/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPhoneBoothsRoute = LayoutPhoneBoothsRouteImport.update({
  id: '/phone-booths',
  path: '/phone-booths',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMqttItemsRoute = LayoutMqttItemsRouteImport.update({
  id: '/mqtt-items',
  path: '/mqtt-items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoothCalendarRoute = LayoutBoothCalendarRouteImport.update({
  id: '/booth-calendar',
  path: '/booth-calendar',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsageReportsTableRoute = LayoutUsageReportsTableRouteImport.update({
  id: '/usage-reports/table',
  path: '/usage-reports/table',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsageReportsChartsRoute =
  LayoutUsageReportsChartsRouteImport.update({
    id: '/usage-reports/charts',
    path: '/usage-reports/charts',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminClientsRoute = LayoutAdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAdminRoute = LayoutAdminAdminRouteImport.update({
  id: '/admin/admin',
  path: '/admin/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/booth-calendar': typeof LayoutBoothCalendarRoute
  '/items': typeof LayoutItemsRoute
  '/mqtt-items': typeof LayoutMqttItemsRoute
  '/phone-booths': typeof LayoutPhoneBoothsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/admin': typeof LayoutAdminAdminRoute
  '/admin/clients': typeof LayoutAdminClientsRoute
  '/usage-reports/charts': typeof LayoutUsageReportsChartsRoute
  '/usage-reports/table': typeof LayoutUsageReportsTableRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/booth-calendar': typeof LayoutBoothCalendarRoute
  '/items': typeof LayoutItemsRoute
  '/mqtt-items': typeof LayoutMqttItemsRoute
  '/phone-booths': typeof LayoutPhoneBoothsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/admin': typeof LayoutAdminAdminRoute
  '/admin/clients': typeof LayoutAdminClientsRoute
  '/usage-reports/charts': typeof LayoutUsageReportsChartsRoute
  '/usage-reports/table': typeof LayoutUsageReportsTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/booth-calendar': typeof LayoutBoothCalendarRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mqtt-items': typeof LayoutMqttItemsRoute
  '/_layout/phone-booths': typeof LayoutPhoneBoothsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/admin': typeof LayoutAdminAdminRoute
  '/_layout/admin/clients': typeof LayoutAdminClientsRoute
  '/_layout/usage-reports/charts': typeof LayoutUsageReportsChartsRoute
  '/_layout/usage-reports/table': typeof LayoutUsageReportsTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/booth-calendar'
    | '/items'
    | '/mqtt-items'
    | '/phone-booths'
    | '/settings'
    | '/'
    | '/admin/admin'
    | '/admin/clients'
    | '/usage-reports/charts'
    | '/usage-reports/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/booth-calendar'
    | '/items'
    | '/mqtt-items'
    | '/phone-booths'
    | '/settings'
    | '/'
    | '/admin/admin'
    | '/admin/clients'
    | '/usage-reports/charts'
    | '/usage-reports/table'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/booth-calendar'
    | '/_layout/items'
    | '/_layout/mqtt-items'
    | '/_layout/phone-booths'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/admin'
    | '/_layout/admin/clients'
    | '/_layout/usage-reports/charts'
    | '/_layout/usage-reports/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/phone-booths': {
      id: '/_layout/phone-booths'
      path: '/phone-booths'
      fullPath: '/phone-booths'
      preLoaderRoute: typeof LayoutPhoneBoothsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mqtt-items': {
      id: '/_layout/mqtt-items'
      path: '/mqtt-items'
      fullPath: '/mqtt-items'
      preLoaderRoute: typeof LayoutMqttItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/booth-calendar': {
      id: '/_layout/booth-calendar'
      path: '/booth-calendar'
      fullPath: '/booth-calendar'
      preLoaderRoute: typeof LayoutBoothCalendarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usage-reports/table': {
      id: '/_layout/usage-reports/table'
      path: '/usage-reports/table'
      fullPath: '/usage-reports/table'
      preLoaderRoute: typeof LayoutUsageReportsTableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/usage-reports/charts': {
      id: '/_layout/usage-reports/charts'
      path: '/usage-reports/charts'
      fullPath: '/usage-reports/charts'
      preLoaderRoute: typeof LayoutUsageReportsChartsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/clients': {
      id: '/_layout/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof LayoutAdminClientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/admin': {
      id: '/_layout/admin/admin'
      path: '/admin/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof LayoutAdminAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBoothCalendarRoute: typeof LayoutBoothCalendarRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMqttItemsRoute: typeof LayoutMqttItemsRoute
  LayoutPhoneBoothsRoute: typeof LayoutPhoneBoothsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminAdminRoute: typeof LayoutAdminAdminRoute
  LayoutAdminClientsRoute: typeof LayoutAdminClientsRoute
  LayoutUsageReportsChartsRoute: typeof LayoutUsageReportsChartsRoute
  LayoutUsageReportsTableRoute: typeof LayoutUsageReportsTableRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBoothCalendarRoute: LayoutBoothCalendarRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMqttItemsRoute: LayoutMqttItemsRoute,
  LayoutPhoneBoothsRoute: LayoutPhoneBoothsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminAdminRoute: LayoutAdminAdminRoute,
  LayoutAdminClientsRoute: LayoutAdminClientsRoute,
  LayoutUsageReportsChartsRoute: LayoutUsageReportsChartsRoute,
  LayoutUsageReportsTableRoute: LayoutUsageReportsTableRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
